### ISSUE TITLE
@loader_path breaks macpack

### ISSUE THREAD

**Issue by lilmike** [chearon/macpack#4] opened 2017-03-05 18:34 UTC
Hi,
Similar to an issue I opened on dylibbundler, I have a library my executable depends on. This library was built in such a way it depends on @loader_path/libxxx. This causes macpack to fail to (I think) find the dependancies for that library. Perhaps something can be done about this?
Thanks,
-Michael.

**Comment by lilmike** [comment] 2017-03-05 18:38
Also, here's the output I get:

Patching MineRacer.app/Contents/MacOS/mineracer
12 total non-system dependencies
liballegro_main.5.2.2.dylib
-> liballegro_main.5.2.2.dylib
-> @loader_path
liballegro_audio.5.2.2.dylib
-> liballegro_audio.5.2.2.dylib
-> @loader_path
liballegro_acodec.5.2.2.dylib
-> liballegro_acodec.5.2.2.dylib
-> @loader_path
-> libFLAC.8.dylib
-> libogg.0.dylib
-> libvorbisfile.3.dylib
-> libvorbis.0.dylib
-> libopusfile.0.dylib
-> libopus.0.dylib
liballegro.5.2.2.dylib
-> liballegro.5.2.2.dylib
liballegro_font.5.2.2.dylib
-> liballegro_font.5.2.2.dylib
-> @loader_path
libogg.0.dylib
-> libogg.0.dylib
libvorbis.0.dylib
-> libvorbis.0.dylib
-> libogg.0.dylib
libvorbisfile.3.dylib
-> libvorbisfile.3.dylib
-> libvorbis.0.dylib
-> libogg.0.dylib
libopus.0.dylib
-> libopus.0.dylib
libopusfile.0.dylib
-> libopusfile.0.dylib
-> libogg.0.dylib
-> libopus.0.dylib
libFLAC.8.dylib
-> libFLAC.8.dylib
@loader_path
Traceback (most recent call last):
  File "/usr/local/bin/macpack", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/macpack/patcher.py", line 155, in main
    loop.run_until_complete(patch(d, dest_path, root_loader_path))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/macpack/patcher.py", line 71, in patch
    shutil.copyfile(str(dep.path), str(dest_path / dep.path.name))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lilmike/@loader_path'

**Comment by chearon** [comment] 2017-03-07 03:47
Hey, thanks for reporting the issue here... macpack should probably handle this scenario. It's actually just supposed to log dependencies it can't find on the filesystem and move on, but I guess this is a case where it doesn't work.

The liballegro in Homebrew doesn't have the same scenario as yours (no `@loader_path` in the tree) but I'll just emulate your scenario by manually patching one of the libraries and then fix it from there

**Comment by lilmike** [comment] 2017-03-19 23:11
Any news? :-).
-Michael.

**Comment by chearon** [comment] 2017-03-20 12:54
No, but I still want to fix this! I spent some time trying to reproduce your scenario a while back and that's where I got stuck, I think. Is the `MineRacer.app` you were patching available for me to download so I can easily reproduce the same error you got?

**Comment by lilmike** [comment] 2017-03-20 16:11
Hi,
Yes, if you go to https://2mb.co/mr, you can get the demo of the game that had that same problem.
Michael.

Sent from my iPhone

On Mar 20, 2017, at 7:54 AM, Caleb Hearon <notifications@github.com<mailto:notifications@github.com>> wrote:


No, but I still want to fix this! I spent some time trying to reproduce your scenario a while back and that's where I got stuck, I think. Is the MineRacer.app you were patching available for me to download so I can easily reproduce the same error you got?

**Comment by chearon** [comment] 2017-03-21 02:36
Ok, I tried running macpack on `Contents/MacOS/mineracer` and the output was wrong. It's a very similar error to yours, so hopefully I found the same problem. I was not able to get your exact output though.

Version 1.0.2:
```
$ macpack mineracer.app/Contents/MacOS/mineracer
Patching /Users/caleb/Downloads/mineracer.app/Contents/MacOS/mineracer
1 total non-system dependency
1       @loader_path -> No dependencies
Traceback (most recent call last):
  File "/usr/local/bin/macpack", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/macpack/patcher.py", line 155, in main
    loop.run_until_complete(patch(d, dest_path, root_loader_path))
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/
base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/macpack/patcher.py", line 71, in patch
    shutil.copyfile(str(dep.path), str(dest_path / dep.path.name))
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.p
y", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/caleb/Code/macpack/@loader_path'
```

Version 1.0.3 released today (the binary on your site is already patched and can't be patched further):
```
$ macpack mineracer.app/Contents/MacOS/mineracer
Some of the paths in the dependency tree could not be resolved
Maybe you already bundled mineracer?
Run with -v to see failed paths
Patching /Users/caleb/Downloads/mineracer.app/Contents/MacOS/mineracer
0 total non-system dependencies

mineracer + 0 dependencies successfully patched
```

To see the failed deps (because they are are already patched) run with *-v*:
```
$ macpack -v --dry-run mineracer.app/Contents/MacOS/mineracer
Some of the paths in the dependency tree could not be resolved
Maybe you already bundled mineracer?
Could not resolve @loader_path/lib/liballegro_main.dylib
Could not resolve @loader_path/lib/liballegro_audio.dylib
Could not resolve @loader_path/lib/liballegro_acodec.dylib
Could not resolve @loader_path/lib/liballegro.dylib
Could not resolve @loader_path/lib/liballegro_font.dylib
Could not resolve @loader_path/lib/libogg.dylib
Could not resolve @loader_path/lib/libvorbis.dylib
Could not resolve @loader_path/lib/libvorbisfile.dylib
Could not resolve @loader_path/lib/libopus.dylib
Could not resolve @loader_path/lib/libopusfile.dylib
Could not resolve @loader_path/lib/libFLAC.dylib
Patching /Users/caleb/Downloads/mineracer.app/Contents/MacOS/mineracer
0 total non-system dependencies
```

Please let me know if it does or doesn't work!

**Comment by chearon** [comment] 2017-03-30 01:56
Hey @lilmike, did you have a chance to test out the latest release? I was pretty sure I had found the issue you were having

**Comment by lilmike** [comment] 2017-03-30 13:00
Hi,
Not yet, but I need to build a new version, so I'll try it out soon.
Michael.

Sent from my iPhone

On Mar 29, 2017, at 8:56 PM, Caleb Hearon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @lilmike<https://github.com/lilmike>, did you have a chance to test out the latest release? I was pretty sure I had found the issue you were having

**Comment by chearon** [comment] 2018-12-10 02:33
Closing because as far as I can tell this is fixed

**Closed as completed by chearon** 2018-12-10 02:33 UTC
